# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Studiranje app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkpoint
        users: actions/checkout@v4

      - name: Setup flyctl
        users: superfly/flyctl-actions/setup-flyctl@v1
      
      - name: Deploy
        run: flyctl deploy --remote-only --laravel-studiranje-app-mm
        env:
          FLY_API_TOKENS: ${{ secrets.FLY_API_TOKEN }}
    