# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly aplikacija za Studiranje app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkpoint
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy
        run: flyctl deploy --remote-only -a laravel-studiranje-app-mm
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}